language: php
php:
 - 5.5
 - 5.4
 - 5.3
before_script:
 - composer install
 - pyrus install pear/PHP_CodeSniffer

script:
 - mkdir -p build/logs
 - vendor/bin/phpcs --standard=PSR2 src/
 - vendor/bin/phpcs --standard=PSR2 tests/
 - cd tests; ./dev-all-tests.sh

after_script:
# - vendor/bin/coveralls -v
